name: Auto Assignment for Issues
run-name: Auto Assignment for Issues

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Assign issue to repo owner
        uses: actions/github-script@v8
        with:
          script: |
            try {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [context.repo.owner]
              });
            } catch (error) {
              core.setFailed(`Failed to assign issue: ${error.message}`);
            }
